### PR TITLE
MT->Human

### PR DESCRIPTION
**Pull request by warchlak**

### CODE REVIEW

**Comment by warchlak** [comment]
It looks like you are ignoring all my submits. Can I expect someone to review my changes someday?

**Comment by mairaw** [comment]
This shouldn't have happened @warchlak. I'll check with the team what's going on.

**Comment by DavidPrio** [comment]
Hello @warchlak . This is so unfortunate situation. We apologize we failed to communicate our work and updates on your contribution. We will dig deep into this and come back to you with details no later than next week.
@gosali , please take a look at this asap. Thanks

**Comment by warchlak** [comment]
Fast You are. If it means to you "asap", the end of cooperation is a good decision.

**Comment by gosali** [comment]
Hi @warchlak ,

We are deeply sorry about this inconvenience. 
We are working on your contributions. Some of them were already accepted and implemented and will be considered on the next localization round.
We expect to have all your accepted contributions implemented by end of the next week.
Unfortunately you closed the PR and we are not able to re-open it and merge it. But Please feel free to submit new PRs. 
Your cooperation is very important for us and it is much appreciate it.

Microsoft C&E Localization Team

**Comment by warchlak** [comment]
PR reopened as new one.

**Pull request closed without merging**
